# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/poky/2.4.2/sysroots/x86_64-pokysdk-linux/usr/bin/cmake

# The command to remove a file.
RM = /opt/poky/2.4.2/sysroots/x86_64-pokysdk-linux/usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/yang/yang_share/ucm_client/pro_ucm_client_cmake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/yang/yang_share/ucm_client/pro_ucm_client_cmake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/poky/2.4.2/sysroots/x86_64-pokysdk-linux/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/poky/2.4.2/sysroots/x86_64-pokysdk-linux/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yang/yang_share/ucm_client/pro_ucm_client_cmake/CMakeFiles /home/yang/yang_share/ucm_client/pro_ucm_client_cmake/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/yang/yang_share/ucm_client/pro_ucm_client_cmake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SoftwareUpdate

# Build rule for target.
SoftwareUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SoftwareUpdate
.PHONY : SoftwareUpdate

# fast build rule for target.
SoftwareUpdate/fast:
	$(MAKE) -f CMakeFiles/SoftwareUpdate.dir/build.make CMakeFiles/SoftwareUpdate.dir/build
.PHONY : SoftwareUpdate/fast

src/filehandle.o: src/filehandle.cpp.o

.PHONY : src/filehandle.o

# target to build an object file
src/filehandle.cpp.o:
	$(MAKE) -f CMakeFiles/SoftwareUpdate.dir/build.make CMakeFiles/SoftwareUpdate.dir/src/filehandle.cpp.o
.PHONY : src/filehandle.cpp.o

src/filehandle.i: src/filehandle.cpp.i

.PHONY : src/filehandle.i

# target to preprocess a source file
src/filehandle.cpp.i:
	$(MAKE) -f CMakeFiles/SoftwareUpdate.dir/build.make CMakeFiles/SoftwareUpdate.dir/src/filehandle.cpp.i
.PHONY : src/filehandle.cpp.i

src/filehandle.s: src/filehandle.cpp.s

.PHONY : src/filehandle.s

# target to generate assembly for a file
src/filehandle.cpp.s:
	$(MAKE) -f CMakeFiles/SoftwareUpdate.dir/build.make CMakeFiles/SoftwareUpdate.dir/src/filehandle.cpp.s
.PHONY : src/filehandle.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/SoftwareUpdate.dir/build.make CMakeFiles/SoftwareUpdate.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/SoftwareUpdate.dir/build.make CMakeFiles/SoftwareUpdate.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/SoftwareUpdate.dir/build.make CMakeFiles/SoftwareUpdate.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/massageparser.o: src/massageparser.cpp.o

.PHONY : src/massageparser.o

# target to build an object file
src/massageparser.cpp.o:
	$(MAKE) -f CMakeFiles/SoftwareUpdate.dir/build.make CMakeFiles/SoftwareUpdate.dir/src/massageparser.cpp.o
.PHONY : src/massageparser.cpp.o

src/massageparser.i: src/massageparser.cpp.i

.PHONY : src/massageparser.i

# target to preprocess a source file
src/massageparser.cpp.i:
	$(MAKE) -f CMakeFiles/SoftwareUpdate.dir/build.make CMakeFiles/SoftwareUpdate.dir/src/massageparser.cpp.i
.PHONY : src/massageparser.cpp.i

src/massageparser.s: src/massageparser.cpp.s

.PHONY : src/massageparser.s

# target to generate assembly for a file
src/massageparser.cpp.s:
	$(MAKE) -f CMakeFiles/SoftwareUpdate.dir/build.make CMakeFiles/SoftwareUpdate.dir/src/massageparser.cpp.s
.PHONY : src/massageparser.cpp.s

src/packagemanagerclient.o: src/packagemanagerclient.cpp.o

.PHONY : src/packagemanagerclient.o

# target to build an object file
src/packagemanagerclient.cpp.o:
	$(MAKE) -f CMakeFiles/SoftwareUpdate.dir/build.make CMakeFiles/SoftwareUpdate.dir/src/packagemanagerclient.cpp.o
.PHONY : src/packagemanagerclient.cpp.o

src/packagemanagerclient.i: src/packagemanagerclient.cpp.i

.PHONY : src/packagemanagerclient.i

# target to preprocess a source file
src/packagemanagerclient.cpp.i:
	$(MAKE) -f CMakeFiles/SoftwareUpdate.dir/build.make CMakeFiles/SoftwareUpdate.dir/src/packagemanagerclient.cpp.i
.PHONY : src/packagemanagerclient.cpp.i

src/packagemanagerclient.s: src/packagemanagerclient.cpp.s

.PHONY : src/packagemanagerclient.s

# target to generate assembly for a file
src/packagemanagerclient.cpp.s:
	$(MAKE) -f CMakeFiles/SoftwareUpdate.dir/build.make CMakeFiles/SoftwareUpdate.dir/src/packagemanagerclient.cpp.s
.PHONY : src/packagemanagerclient.cpp.s

src/usbhandle.o: src/usbhandle.cpp.o

.PHONY : src/usbhandle.o

# target to build an object file
src/usbhandle.cpp.o:
	$(MAKE) -f CMakeFiles/SoftwareUpdate.dir/build.make CMakeFiles/SoftwareUpdate.dir/src/usbhandle.cpp.o
.PHONY : src/usbhandle.cpp.o

src/usbhandle.i: src/usbhandle.cpp.i

.PHONY : src/usbhandle.i

# target to preprocess a source file
src/usbhandle.cpp.i:
	$(MAKE) -f CMakeFiles/SoftwareUpdate.dir/build.make CMakeFiles/SoftwareUpdate.dir/src/usbhandle.cpp.i
.PHONY : src/usbhandle.cpp.i

src/usbhandle.s: src/usbhandle.cpp.s

.PHONY : src/usbhandle.s

# target to generate assembly for a file
src/usbhandle.cpp.s:
	$(MAKE) -f CMakeFiles/SoftwareUpdate.dir/build.make CMakeFiles/SoftwareUpdate.dir/src/usbhandle.cpp.s
.PHONY : src/usbhandle.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... SoftwareUpdate"
	@echo "... edit_cache"
	@echo "... src/filehandle.o"
	@echo "... src/filehandle.i"
	@echo "... src/filehandle.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/massageparser.o"
	@echo "... src/massageparser.i"
	@echo "... src/massageparser.s"
	@echo "... src/packagemanagerclient.o"
	@echo "... src/packagemanagerclient.i"
	@echo "... src/packagemanagerclient.s"
	@echo "... src/usbhandle.o"
	@echo "... src/usbhandle.i"
	@echo "... src/usbhandle.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

